services:
  webclient:
    container_name: webclient
    build:
      context: ./webclient
    ports:
      - '8080:80'
  proxy:
    container_name: proxy 
    build:
      context: ./proxy
    ports: 
      - 3000:3000 
